version: '3.4'

services:
  discordbot:
    image: discordbot
    container_name: theDawg
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    restart: on-failure
    ports:
      - 3000:3000
